[package]
name = "conway"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
gettext-sys = { version = "0.21.3", features = ["gettext-system"] }
ncurses = "6.0.0"
rand = "0.8"
